// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCieerCBycv54wIhuIzCfJMeI2RQK7X9jc',
    appId: '1:219019182751:web:90bd57437d87438b9fd8aa',
    messagingSenderId: '219019182751',
    projectId: 'learnspace-82547',
    authDomain: 'learnspace-82547.firebaseapp.com',
    storageBucket: 'learnspace-82547.firebasestorage.app',
    measurementId: 'G-VDCS0STYHD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBmZpQwljsqATj-t4NyzyObYHnZ4Xhyiow',
    appId: '1:219019182751:android:35a61a3a0b21b8d99fd8aa',
    messagingSenderId: '219019182751',
    projectId: 'learnspace-82547',
    storageBucket: 'learnspace-82547.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDS9WqJjUXgzR9sJ0kFunIZkXX3foVHiBY',
    appId: '1:219019182751:ios:bd9828fd4d4e983b9fd8aa',
    messagingSenderId: '219019182751',
    projectId: 'learnspace-82547',
    storageBucket: 'learnspace-82547.firebasestorage.app',
    iosBundleId: 'com.learsphere.learnsphere',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDS9WqJjUXgzR9sJ0kFunIZkXX3foVHiBY',
    appId: '1:219019182751:ios:bd9828fd4d4e983b9fd8aa',
    messagingSenderId: '219019182751',
    projectId: 'learnspace-82547',
    storageBucket: 'learnspace-82547.firebasestorage.app',
    iosBundleId: 'com.learsphere.learnsphere',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCieerCBycv54wIhuIzCfJMeI2RQK7X9jc',
    appId: '1:219019182751:web:9f57b971bb2f92cf9fd8aa',
    messagingSenderId: '219019182751',
    projectId: 'learnspace-82547',
    authDomain: 'learnspace-82547.firebaseapp.com',
    storageBucket: 'learnspace-82547.firebasestorage.app',
    measurementId: 'G-N9ZH8REB77',
  );
}
